server:
  port: 8002
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: cn.study.vo            # 定义所有操作类的别名所在包
  mapper-locations:                                     # 所有的mapper映射文件
    - classpath:mybatis/mapper/**/*.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.jdbc.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/study8001           # 数据库连接地址
    username: root                                  # 数据库用户名
    password: 123456                            # 数据库连接密码
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
  application:
    name: microcloud-provider-dept

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://edmin:studyjava@eureka-7001.com:7001/eureka,http://edmin:studyjava@eureka-7002.com:7002/eureka,http://edmin:studyjava@eureka-7003.com:7003/eureka
  instance:
#    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
#    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: dept-8002.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址

info:
  app.name: study-microcloud
  company.name: www.study.cn
  build.artifactId: $project.artifactId$
  build.version: $project.verson$




#与springsecurity有关的配置，改用一个project代替
#  security:
#    sessions: stateless #无状态的 Session 设置
#    basic:
#      enabled: true # 启用SpringSecurity的安全配置项
#    user:
#      name: studyjava  # 认证用户名
#      password: hello # 认证密码
#      role:        # 授权角色
#        - USER
